// app/glossario/layout.tsx
import SchemaMarkup from '@/components/SchemaMarkup';
import { faqPage, breadcrumb, SITE_CONFIG } from '@/lib/schema';

const GLOSSARY_TERMS = [
  { term: 'MCMV', answer: 'Programa habitacional do governo federal que oferece subsídios, taxas reduzidas e condições especiais para famílias de baixa e média renda adquirirem imóvel próprio. Dividido em faixas por renda familiar bruta: Faixa 1 (até R$ 3.200), Faixa 2 (até R$ 5.000), Faixa 3 (até R$ 9.600) e Faixa 4 (até R$ 13.000). O financiamento é feito pela Caixa Econômica Federal e banco parceiros, com prazo de até 35 anos.' },
  { term: 'SBPE', answer: 'Modalidade de crédito imobiliário que usa recursos captados pela caderneta de poupança. É a linha mais comum para imóveis de médio e alto padrão (acima dos tetos do MCMV). As taxas variam entre bancos (geralmente 10–12% a.a. + TR), sem subsídio governamental. Aceita FGTS para amortização.' },
  { term: 'SFH', answer: 'Enquadramento legal para financiamentos habitacionais com imóveis de até R$ 2,25 milhões (valor de avaliação) — teto atualizado em outubro/2025. Permite uso do FGTS, limita a taxa nominal a 12% a.a. e exige que o imóvel seja residencial. É o enquadramento padrão do MCMV e de parte do SBPE. A Caixa Econômica Federal financia até 80% do valor do imóvel dentro do SFH.' },
  { term: 'SFI', answer: 'Usado para imóveis acima de R$ 2,25 milhões ou operações com taxas acima de 12% a.a. Não permite uso do FGTS. Inclui instrumentos como CRI (Certificado de Recebíveis Imobiliários). Oferece mais flexibilidade para o credor definir condições contratuais — taxas de mercado, sem vinculação ao SBPE.' },
  { term: 'Crédito Associativo', answer: 'Modalidade em que a Caixa Econômica Federal (ou banco parceiro) contrata o financiamento do comprador ainda na fase de construção. O banco libera recursos diretamente para a construtora conforme o avanço da obra. O comprador paga juros sobre o saldo contratado durante a obra (fase de evolução) e, após o habite-se, inicia as parcelas definitivas de amortização. É a forma mais comum de compra na planta via MCMV.' },
  { term: 'TR', answer: 'A TR (Taxa Referencial) é calculada mensalmente pelo Banco Central a partir da TBF (Taxa Básica Financeira) e aplicada como correção monetária sobre o saldo devedor dos contratos SFH — tanto MCMV quanto SBPE. Atenção: a TR ficou zerada por cerca de 10 anos (2012–2022) devido ao ciclo de juros baixos, o que levou muita gente a acreditar que ela "não existe mais". Isso está errado. Com a alta da Selic, a TR voltou a ser positiva em agosto de 2022 e permanece assim. Em maio de 2026, a TR mensal é de aproximadamente 0,1679%, o que equivale a cerca de 2,06% ao ano. Ao longo de 35 anos, essa correção acumula e pode elevar o saldo devedor significativamente se não for considerada nas simulações.' },
  { term: 'INCC', answer: 'Índice calculado pela FGV que mede a variação do custo de construção civil no Brasil. As parcelas pagas durante a obra (antes do habite-se) são corrigidas mensalmente pelo INCC, o que pode elevar o saldo devedor se a inflação da construção for alta. Após a entrega das chaves, a correção passa a ser pela TR (nos contratos SFH) ou pelo IPCA (em contratos alternativos).' },
  { term: 'CET', answer: 'O CET expressa o custo real anual do crédito imobiliário, incorporando não apenas a taxa de juros nominal mas também seguros obrigatórios (MIP e DFI), tarifa de avaliação do imóvel, TAC e demais encargos. É o número correto para comparar propostas de diferentes bancos. Por lei, os bancos são obrigados a informar o CET antes da assinatura do contrato.' },
  { term: 'LTV', answer: 'Razão entre o valor financiado e o valor de avaliação do imóvel. Por exemplo, um imóvel de R$ 300.000 com financiamento de R$ 240.000 tem LTV de 80%. Cada banco tem limites de LTV por modalidade: MCMV Faixa 1–3 pode chegar a 90%, SBPE geralmente permite até 80%. Quanto menor o LTV, menor o risco para o banco — o que pode resultar em taxas melhores.' },
  { term: 'Taxa Nominal vs. Efetiva', answer: 'A taxa nominal é a informada no contrato (ex: 10,5% a.a.). A taxa efetiva considera o efeito de capitalização composta e é sempre maior. Nos financiamentos imobiliários, as parcelas são calculadas com base na taxa mensal equivalente (taxa_anual/12 em Price, ou taxa simples em SAC), mas o saldo devedor ainda sofre correção pela TR. Sempre compare propostas pela taxa efetiva ou pelo CET.' },
  { term: 'SAC', answer: 'No SAC, o valor amortizado (abatido do saldo devedor) é constante a cada mês. Como os juros incidem sobre um saldo que cai, a parcela total diminui ao longo do tempo. A primeira parcela é mais alta, mas o total pago ao banco é menor comparado ao Price. É o sistema padrão dos financiamentos MCMV e indicado para quem pode pagar mais no início.' },
  { term: 'Price', answer: 'No sistema Price (também chamado Tabela Price ou Sistema Francês), as parcelas são iguais ao longo do contrato. No início, a maior parte da parcela são juros; com o tempo, a proporção de amortização aumenta. Por pagar juros sobre um saldo que demora mais a cair, o custo total é maior que no SAC. É preferido por quem precisa de parcela previsível e menor no início.' },
  { term: 'Amortização', answer: 'A parcela mensal do financiamento é composta de duas partes: juros (calculados sobre o saldo devedor restante) e amortização (valor que de fato abate a dívida). Nos primeiros meses, os juros dominam a parcela. Entender essa composição ajuda a decidir entre usar FGTS para amortizar prazo ou reduzir parcelas — em geral, amortizar o saldo (reduzindo prazo) economiza mais.' },
  { term: 'Saldo Devedor', answer: 'É o montante que você ainda deve ao banco após descontar todas as amortizações pagas até aquele momento. O saldo devedor é corrigido mensalmente pela TR (nos contratos SFH), o que significa que mesmo pagando em dia, ele pode crescer se a TR for elevada. Simular a evolução do saldo devedor ao longo do prazo é essencial para entender o real custo do financiamento.' },
  { term: 'MIP', answer: 'Seguro obrigatório contratado junto ao financiamento. Em caso de morte ou invalidez permanente do mutuário, o MIP quita o saldo devedor remanescente, protegendo a família. O prêmio mensal varia conforme a idade do comprador (quanto mais velho, maior o seguro) e o saldo devedor. É calculado sobre o saldo devedor e reduz ao longo do contrato.' },
  { term: 'DFI', answer: 'Seguro obrigatório que cobre danos físicos estruturais ao imóvel (incêndio, inundação, desabamento). É contratado junto ao banco financiador e protege tanto o comprador quanto o banco (que tem o imóvel como garantia via alienação fiduciária). O prêmio é geralmente fixo e calculado sobre o valor de avaliação do imóvel.' },
  { term: 'ITBI', answer: 'Imposto municipal cobrado na transferência de propriedade do imóvel. Em São Paulo capital, a alíquota é 3% sobre o maior valor entre o valor venal de referência e o valor da transação. Duas isenções importantes em SP: na parte financiada via SFH, até R$ 636.612,50, o ITBI não incide (paga-se só sobre a entrada); no MCMV/primeiro imóvel, há isenção total até R$ 245.527,77 (valor de 2026). A regra varia por município. O pagamento do ITBI é requisito para registrar o imóvel em cartório.' },
  { term: 'TAC', answer: 'Tarifa cobrada pelo banco para cobrir os custos administrativos de análise e liberação do crédito imobiliário. Pode ser paga à vista ou incorporada ao financiamento. Alguns bancos isentam a TAC como estratégia comercial. Faz parte do CET e deve ser considerada na comparação entre propostas.' },
  { term: 'Registro de Imóvel', answer: 'Após a assinatura do contrato de financiamento (escritura pública ou instrumento particular com força de escritura), o comprador deve registrar o imóvel no Cartório de Registro de Imóveis (CRI). O custo varia por estado (em SP, aproximadamente 1% do valor do imóvel). Somente após o registro o comprador é legalmente considerado o proprietário.' },
  { term: 'Habite-se', answer: 'Documento expedido pela prefeitura municipal após vistoria que atesta que a construção foi concluída de acordo com o projeto aprovado e está em condições de ser habitada. Sem o habite-se, o imóvel não pode ser registrado nem financiado. É o marco que encerra a fase de obra no crédito associativo e inicia as parcelas definitivas de amortização.' },
  { term: 'RI', answer: 'O Registro de Imóveis é o cartório que mantém a matrícula de cada imóvel — documento que reúne todo o histórico de proprietários, ônus, penhoras, hipotecas e alienações. Antes de comprar, é essencial solicitar a certidão de matrícula atualizada (últimas 24 horas) para verificar a titularidade e a existência de gravames. É no RI que a alienação fiduciária (garantia do banco) é registrada.' },
  { term: 'RI de Incorporação', answer: 'Antes de vender qualquer unidade na planta, a construtora/incorporadora deve registrar a incorporação no Cartório de Registro de Imóveis. Esse registro inclui: memorial descritivo, planta aprovada, fração ideal do terreno por unidade e quadro de áreas. Comprar de uma incorporação com RI garante que o empreendimento está legalmente constituído e que as unidades podem ser individualizadas futuramente.' },
  { term: 'SICAQ', answer: 'Sistema da Caixa Econômica Federal que centraliza as informações do contrato de crédito associativo: cronograma de obra, repasses, vistorias e situação financeira do comprador. O acompanhamento via SICAQ permite verificar se os repasses à construtora estão dentro do cronograma e se há inconsistências que possam travar o financiamento.' },
  { term: 'Alienação Fiduciária', answer: 'Modalidade de garantia usada nos financiamentos imobiliários modernos. O comprador usa o imóvel mas a propriedade formal fica com o banco (credor fiduciário) até a quitação total da dívida. Em caso de inadimplência, o banco pode executar a garantia de forma extrajudicial (sem precisar ir à Justiça), o que torna o processo mais rápido. Após a quitação, o banco emite o termo de quitação e o comprador registra a plena propriedade no RI.' },
  { term: 'FGTS', answer: 'Fundo constituído por depósitos mensais do empregador (8% do salário bruto). O saldo pode ser usado na compra de imóvel residencial (SFH) para: (1) composição da entrada, (2) amortização do saldo devedor, ou (3) pagamento de até 80% das prestações mensais por até 12 meses seguidos. Regras: imóvel dentro do SFH (até R$ 2,25 milhões — teto atualizado em out/2025), comprador sem outro imóvel financiado no SFH, mínimo 3 anos de vínculo empregatício com FGTS.' },
  { term: 'FGTS Futuro', answer: 'Lançado em 2023, o FGTS Futuro permite que o mutuário use os depósitos mensais futuros de FGTS (ainda não existentes) para complementar a renda e aumentar a capacidade de financiamento. Os depósitos futuros são dados em garantia ao banco, que os utiliza para abater a parcela mensal. É especialmente vantajoso para trabalhadores CLT com renda mais baixa que se enquadram no MCMV Faixa 1 e 2.' },
  { term: 'Subsídio MCMV', answer: 'O subsídio é um benefício não reembolsável concedido pelo governo federal aos compradores do MCMV. Funciona como um desconto no valor do imóvel: o comprador financia apenas o restante. O valor máximo varia por faixa de renda, município e valor do imóvel. Na Faixa 1, o subsídio pode chegar a R$ 55.000; na Faixa 2, também até R$ 55.000 (decrescente conforme renda e valor do imóvel). O subsídio é concedido uma única vez por família.' },
  { term: 'Evolução de Obra', answer: 'Durante a fase de construção, a Caixa Econômica Federal libera o financiamento parceladamente para a construtora conforme o andamento da obra (medições periódicas). O comprador paga mensalmente apenas os juros sobre o saldo já liberado — não há amortização nessa fase. Esse valor cresce à medida que mais recursos são repassados. Após o habite-se, o comprador passa a pagar a parcela completa (amortização + juros) sobre o saldo total contratado.' },
  { term: 'SIOPI', answer: 'O SIOPI (Sistema de Orçamento e Planejamento de Obras da CEF) define a curva típica de evolução física de empreendimentos habitacionais. A CEF usa essa curva para calcular o ritmo de liberação de recursos ao longo da obra. A curva é "S-shaped": começo e fim mais lentos, aceleração no meio. Em simulações, permite estimar os juros de evolução mensais antes mesmo do início da obra.' },
  { term: 'Cronograma Físico-Financeiro', answer: 'Documento obrigatório do crédito associativo que discrimina, mês a mês, o percentual de obra previsto e o valor de repasse correspondente. A Caixa Econômica Federal realiza vistorias periódicas para validar se o avanço físico real coincide com o previsto. Atrasos na obra podem travar repasses, e o comprador deve acompanhar isso via SICAQ.' },
  { term: 'Interveniente Quitante', answer: 'Quando o comprador comprou diretamente da construtora (sem crédito associativo) e depois quer financiar pelo banco, o banco atua como interveniente quitante: paga o saldo devido à construtora e assume a posição de credor. Permite regularizar contratos de gaveta ou financiamentos próprios da incorporadora.' },
  { term: 'Distrato', answer: 'O distrato é o cancelamento do contrato de compra de imóvel na planta. A Lei do Distrato (13.786/2018) regulamenta o processo: se o comprador desistir, a incorporadora pode reter entre 25% e 50% dos valores pagos (dependendo do regime patrimonial do empreendimento) e devolver o restante em até 180 dias após o distrato. Se a construtora atrasar a entrega, o comprador pode pedir o distrato e receber de volta tudo que pagou com correção.' },
];

export default function GlossarioLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const schemas = [
    faqPage({
      url: `${SITE_CONFIG.domain}/glossario`,
      title: 'Glossário de Financiamento Imobiliário',
      description: '32 termos do financiamento imobiliário explicados de forma clara e objetiva.',
      questions: GLOSSARY_TERMS.map(term => ({
        name: term.term,
        answer: term.answer,
      })),
    }),
    breadcrumb([
      { name: 'Início', url: SITE_CONFIG.domain },
      { name: 'Glossário', url: `${SITE_CONFIG.domain}/glossario` },
    ]),
  ];

  return (
    <>
      <SchemaMarkup schemas={schemas} />
      {children}
    </>
  );
}
